data-sources:
  dataSources:
    - name: data-base-1
      strategy: postgres
      url: jdbc:postgresql://localhost:5432/postgres
      table: users
      user: postgres
      password: admin
      mapping:
        id: user_id
        username: login
        name: first_name
        surname: last_name
    - name: data-base-2
      strategy: postgres
      url: jdbc:postgresql://localhost:5432/postgres2
      table: user_table
      user: postgres
      password: admin
      mapping:
        id: ldap_id
        username: ldap_login
        name: name
        surname: surname